// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tommy.chatbot.domain;

import com.tommy.chatbot.domain.Customer;

privileged aspect Customer_Roo_JavaBean {
    

    
}
