// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tommy.chatbot.domain;

import org.springframework.beans.factory.annotation.Configurable;

import javax.persistence.*;

privileged aspect Disease_Roo_Jpa_Entity {

    declare @type: Disease: @Configurable;

    declare @type: Disease: @Entity;
    
    declare @type: Disease: @Table(name = "disease");


    
}
